### Test root endpoint
GET http://localhost:7007/api/v1/

###

### Get all poems
GET http://localhost:7007/api/v1/poems

###

### Create new a new poem
POST http://localhost:7076/api/v1/poems
Content-Type: application/json

[
  {
    "author": "Alice",
    "content": "In a galaxy, far far away, there was a planet called pluto"
  }
]

###